version: '3'

services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap-server
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ORGANISATION=AWTC
      - LDAP_DOMAIN=awtc.com
      - LDAP_ADMIN_PASSWORD=adminawtc1234
      - LDAP_CONFIG_PASSWORD=config
      - LDAP_RFC2307BIS_SCHEMA=false
    volumes:
      # - ./ldap-seed:/container/service/slapd/assets/config/bootstrap/ldif/custom
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    ports:
      - "8081:80"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap-server
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap

volumes:
  ldap-data:
  ldap-config:
